name: rotanatravelapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.5.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  http_parser: ^4.1.2
  flutter_stripe: ^10.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  toyyibpay: ^2.1.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/rotana_logo.png      # wide logo for screens (use your provided image)
    - assets/images/rotana_icon.png      # square/cropped 1024x1024 PNG for app icon

flutter_launcher_icons:
  android: "adaptive"
  ios: true
  image_path_android: "assets/images/rotana_icon.png"
  image_path_ios: "assets/images/rotana_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/rotana_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/rotana_logo.png
  android_12:
    color: "#FFFFFF"

  
